### ISSUE TITLE
Where do you include the package?

### ISSUE THREAD

**Issue by anseljh** [thruflo/pyramid_redis#1]
In README.md, you say:

```
and then include the package:
config.include('pyramid_redis')
```

but where do you do that? I have a guess, but it would be great to state it explicitly and save folks some time and pain.

Thanks!

**Comment by thruflo** [comment]
The word "include" is [hyperlinked to the api docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.include), which include an example of where you include a package.   

I suppose http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/configuration.html might be clearer.  Do feel free to revise for clarity and make a pull request.
